baseURL = "https://ku5e.com/"
languageCode = "en-us"
title = "ku5e | Cybersecurity Portfolio"
theme = "PaperMod"

[params]
    author = "Mario Martinez Jr."

[params.assets]
    favicon = "/assets/favicon.ico"
    favicon16x16 = "/assets/favicon-16x16.png"
    favicon32x32 = "/assets/favicon-32x32.png"
    apple_touch_icon = "/assets/apple-touch-icon.png"
    safari_pinned_tab = "/assets/safari-pinned-tab.svg"   

[services]
  [services.googleAnalytics]
    ID = "G-3M2FR31Y15"
